### ISSUE TITLE
Optionally disable parser route dispatching

### ISSUE THREAD

**Issue by molst** [anmonteiro/compassus#12]
The [official remote sync tutorial](https://github.com/omcljs/om/wiki/Remote-Synchronization-Tutorial) is currently THE working tutorial for how to pretty easily get remote reads working with om.next. The [other tutorials](https://awkay.github.io/om-tutorial/#!/om_tutorial.G_Remote_Fetch)  aim to go deeper, but are not finished.

The official tutorial requires that the read function dispatches on all keys in the query tree, but when using compassus only the top route keys get dispatched. This makes it much harder to get remote reads working because you either need to use an exotic dispatch function (looking at a larger query structure) or parse the whole ast for the route in the send function when putting remote queries to the send channel.

If compassus could be configured to dispatch on all subkeys in the query tree it would likely play well with the mainstream usecase in the official tutorial.

**Comment by Peeja** [comment]
I think you may be missing something significant about how the parser works. The parser, ordinarily, doesn't dispatch on all of the subkeys in the query. It only dispatches on the keys at the _top level_ of the query. So, if your root query is

``` clj
[:a
 {:b [:b/foo
      {:b/bar [:bar/qux]}]}
 :c]
```

your `read` will be called three times, with `:a`, `:b`, and `:c`. The `:b` call will have the `query` set to `[:b/foo {:b/bar [:bar/qux]}]`. If you can resolve that whole query all at once, say with a call to `db->tree`, you can do that. Otherwise, you may want to call the `parser` recursively from there to dispatch your `read` on `:b/foo` and `:b/bar`.

The only effect Compassus has is that it wraps your query to be under the route key. That is, if the query above is the query of your route component, the actual query your parser sees is

``` clj
[{:some/route
  [:a
   {:b [:b/foo
        {:b/bar [:bar/qux]}]}
   :c]}]
```

This is why the parser only invokes your `read` once, and only for the key `:some/route`.

It makes sense to want your `read` to dispatch on the keys of the route query, and ignore the route key itself. I don't think there's a case where it makes sense for your read to get the route key _and_ the keys nested under it. Your `read` would be delivering a value for, for instance, `:a` in two different places: once as part of the `:some/route` read and once as the `:a` read. You really want one or the other.

To do this at CircleCI, we've done the following:

``` clj
(defn flattening-parser
  "Takes a parser. Returns a parser which ignores the root keys of the queries
  it's given, and reads the keys joined to those keys as if they were root keys,
  using the given parser.

  This is particularly useful when using Compassus. Compassus has its own parser
  which calls your parser. The root query it passes to your parser has a single
  key, which is the current route, which is joined to that route component's
  query. That is, if the current route is :app/home and that route matches the
  following component:

  (defui Home
    static IQuery
    (query [this]
      [{:some/data [:some/property]}]))

  then Compassus will ask your parser to read the query:

  [{:app/home [{:some/data [:some/property]}]}]

  If you don't care about the route key, and you'd like your parser to
  treat :some/data as a root-level key in the query, wrap your parser in
  flattening-parser. Your parser will instead read the query:

  [{:some/data [:some/property]}]"
  [parser]
  (om-next/parser
   {:read (fn [{:keys [query target] :as env} key params]
            (if-not target
              {:value (parser env query)}
              {target (let [subquery (parser env query target)]
                        (when (seq subquery)
                          (parser/expr->ast {key subquery})))}))
    :mutate (fn [{:keys [ast target] :as env} key params]
              (let [tx [(om-next/ast->query ast)]]
                (if-not target
                  (let [{:keys [result ::om-next/error] :as ret}
                        (get (parser env tx) key)]
                    {:value (dissoc ret :result ::om-next/error)
                     :action #(or result (throw error))})
                  (let [[ret] (parser env tx target)]
                    {target (cond-> ret
                              (some? ret) parser/expr->ast)}))))}))


(def parser (flattening-parser (om-next/parser {:read read :mutate mutate})))
```

The parser that `flattening-parser` wraps behaves the way I believe you'd like, and the one it returns behaves the way Compassus likes.

This is the behavior that I think Compassus should optionally provide. I think providing it like this, along the same lines as `compassus-merge`, would be a good way to do it.

There's another wrinkle when it comes to _remotes_, though: the remote query is still wrapped in `:some/route`. Currently there's no way around that without modifying Compassus, because [Compassus only supports a single key in the root of the remote query](https://github.com/compassus/compassus/blob/master/src/main/compassus/core.cljc#L181). We use query roots and `om/process-roots` to deal with that, but it would be nice to have Compassus support a way that doesn't require that.

**Comment by molst** [comment]
Thanks for making this a lot clearer! Using this function took me closer to what I was expecting. And you're correct, the remotes wrinkle is there although it seems manageable.

**Comment by anmonteiro** [comment]
I'm ready to work on this. The problem I'm facing is:
- should this be an option directly to the `compassus.core/application` config map parameter?
- how should we name it? 

Feedback very appreciated!

**Comment by anmonteiro** [comment]
One idea would be a `:parser-type` key in the configuration map which would default to the current behavior, but could be changed to `:pass-through` or whatever. 

One benefit of this is that it would allow for future backwards compatible changes if we come up with another behavior for the parser.

**Comment by Peeja** [comment]
I'd love to be able to just refer to the parser builder (of my choice) directly, much like how you can choose to use `compassus-merge`. I'm not sure there's a great way to do that that's backwards-compatible, though.

That would mean that the user could build their own complete parser to hand to Om if they really wanted to, or other libraries could theoretically provide alternatives. Feels nicer to me than providing a closed set of options.

**Comment by anmonteiro** [comment]
fixed https://github.com/compassus/compassus/commit/8db377181842674334914ccf51fba0ab94e271c0.

Also fixed the dispatching on a single remote key.
